### ISSUE TITLE
Segementation fault: 11

### ISSUE THREAD

**Issue by eduncan911** [kleetus/bitcoin_wallet_exporter#1]
Trying to poke at this and getting an error:

```
$ ./exporter -d data/wallet.dat -o data/wallet.json
call implies an access method which is inconsistent with previous calls

Searching the database for master keys and private keys...
Segmentation fault: 11
```

Note that i get the same error when using pywallet.py.  So, I'm thinking it may be related to the Homebrew installation of Berkeley-DB:

```
$ brew info berkeley-db
berkeley-db: stable 6.2.23 (bottled)
High performance key/value database
https://www.oracle.com/technology/products/berkeley-db/index.html
/usr/local/Cellar/berkeley-db/6.2.23 (5,629 files, 115.7MB) *
  Poured from bottle on 2017-03-16 at 16:01:42
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/berkeley-db.rb
==> Requirements
Build: java ✔
Optional: java ✔
```

Thoughts?

Also, while I have you...

My goal is to extra my Private Keys from my collection of wallet.dat files.  I see the README says this doesn't care about Master Passphrases.

So... How would I decrypt them with this tool, using the proper master Passphrase?  (or some other tool)

**Comment by danhealy** [comment]
did you ever figure out the issue?

I can't get pywallet to work with homebrew, either...

**Comment by mikejnpc** [comment]
Hey guys just wondering if there is a assoc fix for the pthreads.... 
thanks


gcc -o exporter exporter.o db-4.8.30.NC/build_unix/libdb.a
/usr/bin/ld: db-4.8.30.NC/build_unix/libdb.a(os_yield.o): in function `__os_yield':
os_yield.c:(.text+0xc9): undefined reference to `pthread_yield'
/usr/bin/ld: db-4.8.30.NC/build_unix/libdb.a(repmgr_posix.o): in function `__repmgr_thread_start':
repmgr_posix.c:(.text+0x389): undefined reference to `pthread_attr_setstacksize'
/usr/bin/ld: repmgr_posix.c:(.text+0x3a3): undefined reference to `pthread_create'
/usr/bin/ld: db-4.8.30.NC/build_unix/libdb.a(repmgr_posix.o): in function `__repmgr_thread_join':
repmgr_posix.c:(.text+0x41b): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make: *** [Makefile:2: all] Error 1

**Comment by eduncan911** [comment]
I had moved on from this years ago.  I'll close it as i can't be the OP for this any longer.

**Comment by mikejnpc** [comment]
ah i see.. well if i could get the build prior to that i would appreciate it :D  
thank you regardless
